export const toursData = [
  {
    id: 1,
    name: "Tour Aa",
    price: 150,
    rating: 4.5,
    days: 5,
    guide: "Jinson Medina",
    images: ["/static/quito.jpg"],
    destination: "Quito",
  },
  {
    id: 2,
    name: "Tour A",
    price: 150,
    rating: 4.5,
    days: 5,
    guide: "Helton QUezada",
    images: ["/static/quito.jpg"],
    destination: "Guayaquil",
  },
  {
    id: 3,
    name: "Tour B",
    price: 200,
    rating: 5.0,
    days: 7,
    guide: "Elias Saquinga",
    images: ["/static/quito2.jpg"],
    destination: "Cuenca",
  },
  {
    id: 4,
    name: "Tour C",
    price: 180,
    rating: 4.8,
    days: 6,
    guide: "Carlos Vera",
    images: ["/static/quito2.jpg"],
    destination: "Perdenales",
  },
  {
    id: 5,
    name: "Tour D",
    price: 180,
    rating: 4.8,
    days: 6,
    guide: "Messi Muñoz",
    images: ["/static/quito2.jpg"],
    destination: "Galápagos",
  },
  {
    id: 6,
    name: "Tour E",
    price: 200,
    rating: 4.7,
    days: 8,
    guide: "Luis González",
    images: ["/static/quito3.jpg"],
    destination: "Baños",
  },
  {
    id: 7,
    name: "Tour F",
    price: 160,
    rating: 4.3,
    days: 4,
    guide: "María Sánchez",
    images: ["/static/quito3.jpg"],
    destination: "Quito",
  },
  {
    id: 8,
    name: "Tour G",
    price: 220,
    rating: 4.9,
    days: 9,
    guide: "Diego Alvarado",
    images: ["/static/quito.jpg"],
    destination: "Baños",
  },
  {
    id: 9,
    name: "Tour H",
    price: 170,
    rating: 4.6,
    days: 5,
    guide: "Laura Pérez",
    images: ["/static/quito4.jpg"],
    destination: "Guayaquil",
  },
  {
    id: 10,
    name: "Tour I",
    price: 190,
    rating: 4.4,
    days: 7,
    guide: "Andrés Mendoza",
    images: ["/static/quito5.jpg"],
    destination: "Perdenales",
  },
  {
    id: 11,
    name: "Tour J",
    price: 180,
    rating: 4.5,
    days: 6,
    guide: "Isabel López",
    images: ["/static/quito3.jpg"],
    destination: "Quito",
  },
  {
    id: 12,
    name: "Tour K",
    price: 160,
    rating: 4.2,
    days: 5,
    guide: "Juan Rodriguez",
    images: ["/static/quito4.jpg"],
    destination: "Guayaquil",
  },
  {
    id: 13,
    name: "Tour L",
    price: 210,
    rating: 4.8,
    days: 7,
    guide: "Ana Martinez",
    images: ["/static/quito5.jpg"],
    destination: "Cuenca",
  },
  {
    id: 14,
    name: "Tour M",
    price: 190,
    rating: 4.6,
    days: 6,
    guide: "Pedro Alvarado",
    images: ["/static/quito3.jpg"],
    destination: "Perdenales",
  },
  {
    id: 15,
    name: "Tour N",
    price: 170,
    rating: 4.4,
    days: 8,
    guide: "Mónica Sánchez",
    images: ["/static/quito4.jpg"],
    destination: "Galápagos",
  },
  {
    id: 16,
    name: "Tour O",
    price: 200,
    rating: 4.7,
    days: 5,
    guide: "Carlos Pérez",
    images: ["/static/quito5.jpg"],
    destination: "Quito",
  },
  {
    id: 17,
    name: "Tour P",
    price: 180,
    rating: 4.3,
    days: 6,
    guide: "Fernanda Gomez",
    images: ["/static/quito3.jpg"],
    destination: "Guayaquil",
  },
  {
    id: 18,
    name: "Tour Q",
    price: 220,
    rating: 4.9,
    days: 7,
    guide: "Daniel Rodriguez",
    images: ["/static/quito4.jpg"],
    destination: "Cuenca",
  },
  {
    id: 19,
    name: "Tour R",
    price: 160,
    rating: 4.6,
    days: 5,
    guide: "Carla Alvarado",
    images: ["/static/quito5.jpg"],
    destination: "Perdenales",
  },
  {
    id: 20,
    name: "Tour S",
    price: 190,
    rating: 4.4,
    days: 8,
    guide: "Rodrigo Mendoza",
    images: ["/static/quito3.jpg"],
    destination: "Galápagos",
  },
];

export const destinationsData = [
  {
    id: 1,
    name: "Quito",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
  {
    id: 2,
    name: "Guayaquil",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
  {
    id: 3,
    name: "Cuenca",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
  {
    id: 4,
    name: "Galápagos",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
  {
    id: 5,
    name: "Baños",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
  {
    id: 6,
    name: "Perdenales",
    tours: [],
    images: ["/static/quito.jpg", "/static/quito2.jpg"],
  },
];
toursData.forEach(tour => {
  const destination = destinationsData.find(dest => dest.name.toLowerCase() === tour.destination.toLowerCase());
  if (destination) {
    destination.tours.push(tour);
  }
});